CACHE_DIR: .cache
DATA_DIR: ds003020
RUNS_DIR: runs
# e.g. for mac usually /Applications/Inkscape.app/Contents/MacOS/inkscape
INKSCAPE_PATH: /path/to/inkscape
# find this by using /path/to/inkscape --version
INKSCAPE_VERSION: X.Y.Z
TR_LEN: 2.0
STORIES:
  [
    alternateithicatom,
    souls,
    avatar,
    legacy,
    odetostepfather,
    undertheinfluence,
    howtodraw,
    myfirstdaywiththeyankees,
    naked,
    life,
    stagefright,
    tildeath,
    fromboyhoodtofatherhood,
    sloth,
    exorcism,
    haveyoumethimyet,
    adollshouse,
    inamoment,
    theclosetthatateeverything,
    adventuresinsayingyes,
    buck,
    swimmingwithastronauts,
    thatthingonmyarm,
    eyespy,
    itsabox,
    hangtime,
    wheretheressmoke,
  ]
# this set to be used with replication experiment 1
# the following stories in the original list contain nans:
# myfirstdaywiththeyankees, naked, life, fromboyhoodtofatherhood
# added stories (selected randomly):
# leavingbaghdad, comingofageondeathrow, againstthewind, forgettingfear
STORIES_2:
  [
    alternateithicatom,
    souls,
    avatar,
    legacy,
    odetostepfather,
    undertheinfluence,
    howtodraw,
    stagefright,
    tildeath,
    sloth,
    exorcism,
    haveyoumethimyet,
    adollshouse,
    inamoment,
    theclosetthatateeverything,
    adventuresinsayingyes,
    buck,
    swimmingwithastronauts,
    thatthingonmyarm,
    eyespy,
    itsabox,
    hangtime,
    wheretheressmoke,
    leavingbaghdad, # ADDED
    comingofageondeathrow, # ADDED
    againstthewind, #ADDED
    forgettingfear, #ADDED
  ]
