site_name: The Encoders
site_author: Kristijan
site_url: https://gabrielkp.com/enc
repo_url: https://github.com/GabrielKP/enc
nav:
  - "Home": "index.md"
  - "Report":
      - Intro: https://kristijanarmeni.github.io/encoders_report/report" target="_blank
  - "Documentation":
      - "Run all": "run_all.md"
      - "Main": "main.md"
      - "Regression": "regression.md"
      - "Features": "features.md"
      - "Data": "data.md"
      - "Utils": "utils.md"

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - content.code.copy
    - toc.integrate

plugins:
  - mkdocstrings:
      handlers:
        python:
          paths: [src] # search packages in the src folder
          options:
            show_root_heading: false
            show_category_heading: true
            show_root_full_path: true
            heading_level: 2
            docstring_style: numpy

markdown_extensions:
  - pymdownx.snippets
