#!/bin/bash
#SBATCH --job-name=repli-bootstrap_UTS02-13-eng1000.script
#SBATCH --time=36:00:00
#SBATCH --mem 40GB
#SBATCH --partition=parallel
#SBATCH --signal=USR2
#SBATCH --nodes=1
#SBATCH --cpus-per-task=8

# set environment (user-specific)
ml anaconda3/2024.02-1
conda activate enc

# call the main routine (assumes code is installed)
python -m encoders.run_all \
--subject UTS02 \
--feature eng1000 \
--n_train_stories 13 \
--test_story wheretheressmoke \
--cross_validation 'simple' \
--interpolation 'lanczos' \
--ridge_implementation 'ridge_chunkbootstrap' \
--n_repeats 15 \
--ndelays 4 \
--nboots 20 \
--chunklen 10 \
--nchunks 10 \
--use_corr \
--no_keep_train_stories_in_mem \
--run_folder_name 2025-07-08_09-08_698679 \
